name: Docker Build automate

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: code checkout
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

      - name: setup Java
        uses: actions/checkout@v7
      - uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: latest
      - run: java --version

      - name: build war
        run: ./mvn clean install -DskipTests
        
      - name: login to github
        run: docker login -u "{{SECRET.DOCKER_USERNAME}}"  --password-stdin

      - name: push docker image

      - name: deploy to EC2 server
      
